-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 22:47:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema askus_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema askus_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `askus_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `askus_db` ;

-- -----------------------------------------------------
-- Table `askus_db`.`vai_tro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`vai_tro` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ma_vai_tro` VARCHAR(20) NOT NULL,
  `ten_vai_tro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`nguoi_dung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`nguoi_dung` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ho_ten` VARCHAR(30) NOT NULL,
  `tai_khoan` VARCHAR(200) NOT NULL,
  `mat_khau` VARCHAR(200) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `so_dien_thoai` VARCHAR(10) NULL,
  `vai_tro_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nguoi_dung_vai_tro1_idx` (`vai_tro_id` ASC) VISIBLE,
  UNIQUE INDEX `tai_khoan_UNIQUE` (`tai_khoan` ASC) VISIBLE,
  CONSTRAINT `fk_nguoi_dung_vai_tro1`
    FOREIGN KEY (`vai_tro_id`)
    REFERENCES `askus_db`.`vai_tro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`bai_viet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`bai_viet` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nguoi_dung_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bai_viet_nguoi_dung1_idx` (`nguoi_dung_id` ASC) VISIBLE,
  CONSTRAINT `fk_bai_viet_nguoi_dung1`
    FOREIGN KEY (`nguoi_dung_id`)
    REFERENCES `askus_db`.`nguoi_dung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`trang_thai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`trang_thai` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ten_trang_thai` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`the_loai_bai_viet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`the_loai_bai_viet` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ma_the_loai` VARCHAR(20) NOT NULL,
  `ten_the_loai` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`binh_luan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`binh_luan` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `noi_dung` LONGTEXT NOT NULL,
  `bai_viet_id` BIGINT UNSIGNED NOT NULL,
  `nguoi_dung_id` BIGINT UNSIGNED NOT NULL,
  `binh_luan_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_binh_luan_bai_viet1_idx` (`bai_viet_id` ASC) VISIBLE,
  INDEX `fk_binh_luan_nguoi_dung1_idx` (`nguoi_dung_id` ASC) VISIBLE,
  INDEX `fk_binh_luan_binh_luan1_idx` (`binh_luan_id` ASC) VISIBLE,
  CONSTRAINT `fk_binh_luan_bai_viet1`
    FOREIGN KEY (`bai_viet_id`)
    REFERENCES `askus_db`.`bai_viet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binh_luan_nguoi_dung1`
    FOREIGN KEY (`nguoi_dung_id`)
    REFERENCES `askus_db`.`nguoi_dung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binh_luan_binh_luan1`
    FOREIGN KEY (`binh_luan_id`)
    REFERENCES `askus_db`.`binh_luan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`binh_luan_chi_tiet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`binh_luan_chi_tiet` (
  `binh_luan_id` BIGINT UNSIGNED NOT NULL,
  `trang_thai_id` TINYINT UNSIGNED NOT NULL,
  `thoi_gian` TIMESTAMP NOT NULL,
  INDEX `fk_binh_luan_chi_tiet_binh_luan1_idx` (`binh_luan_id` ASC) VISIBLE,
  INDEX `fk_binh_luan_chi_tiet_trang_thai1_idx` (`trang_thai_id` ASC) VISIBLE,
  PRIMARY KEY (`binh_luan_id`, `trang_thai_id`),
  CONSTRAINT `fk_binh_luan_chi_tiet_binh_luan1`
    FOREIGN KEY (`binh_luan_id`)
    REFERENCES `askus_db`.`binh_luan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_binh_luan_chi_tiet_trang_thai1`
    FOREIGN KEY (`trang_thai_id`)
    REFERENCES `askus_db`.`trang_thai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`bai_viet_chi_tiet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`bai_viet_chi_tiet` (
  `bai_viet_id` BIGINT UNSIGNED NOT NULL,
  `trang_thai_id` TINYINT UNSIGNED NOT NULL,
  `thoi_gian` TIMESTAMP NOT NULL,
  `tieu_de` VARCHAR(150) NOT NULL,
  `noi_dung` LONGTEXT NOT NULL,
  `the_loai_bai_viet_id` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_bai_viet_chi_tiet_bai_viet1_idx` (`bai_viet_id` ASC) VISIBLE,
  INDEX `fk_bai_viet_chi_tiet_trang_thai1_idx` (`trang_thai_id` ASC) VISIBLE,
  PRIMARY KEY (`bai_viet_id`, `trang_thai_id`),
  INDEX `fk_bai_viet_chi_tiet_the_loai_bai_viet1_idx` (`the_loai_bai_viet_id` ASC) VISIBLE,
  CONSTRAINT `fk_bai_viet_chi_tiet_bai_viet1`
    FOREIGN KEY (`bai_viet_id`)
    REFERENCES `askus_db`.`bai_viet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bai_viet_chi_tiet_trang_thai1`
    FOREIGN KEY (`trang_thai_id`)
    REFERENCES `askus_db`.`trang_thai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bai_viet_chi_tiet_the_loai_bai_viet1`
    FOREIGN KEY (`the_loai_bai_viet_id`)
    REFERENCES `askus_db`.`the_loai_bai_viet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`the_loai_bao_cao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`the_loai_bao_cao` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ma_the_loai` VARCHAR(20) NOT NULL,
  `ten_the_loai` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `askus_db`.`bao_cao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `askus_db`.`bao_cao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nguoi_dung_id` BIGINT UNSIGNED NOT NULL,
  `the_loai_bao_cao_id` TINYINT UNSIGNED NOT NULL,
  `bai_viet_id` BIGINT UNSIGNED NOT NULL,
  `thoi_gian` TIMESTAMP NOT NULL,
  INDEX `fk_bao_cao_nguoi_dung_idx` (`nguoi_dung_id` ASC) VISIBLE,
  INDEX `fk_bao_cao_the_loai_bao_cao1_idx` (`the_loai_bao_cao_id` ASC) VISIBLE,
  INDEX `fk_bao_cao_bai_viet1_idx` (`bai_viet_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bao_cao_nguoi_dung`
    FOREIGN KEY (`nguoi_dung_id`)
    REFERENCES `askus_db`.`nguoi_dung` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bao_cao_the_loai_bao_cao1`
    FOREIGN KEY (`the_loai_bao_cao_id`)
    REFERENCES `askus_db`.`the_loai_bao_cao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bao_cao_bai_viet1`
    FOREIGN KEY (`bai_viet_id`)
    REFERENCES `askus_db`.`bai_viet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
